config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#users controller
  get '/mypage', to: 'users#show'
  patch '/users', to: 'users#change'
  patch '/retire', to: 'users#retire',as: 'retire'
#users/registrations controller
  devise_scope :user do
    # get "sign_up", :to => "users/registrations#new"
    # get "sign_in", :to => "users/sessions#new"
    # get "sign_out", :to => "users/registrations#destroy"
    get 'users/unsubscribe', to: 'users/registrations#unsubscribe'
    get 'users/unsubscribe/complete', to: 'users/registrations#complete'
  end
#orders controller
  get '/order', to: 'orders#order'
  post '/order/confirmation', to: 'orders#confirmation'
  put '/order/confirmation', to: 'orders#create'
  post '/order', to: 'orders#create'
  get '/order/complete', to: 'orders#complete'
#items controller
  # resources :items, only:[:show]  #reviews controllerに移動してあります！！！！！！！！！
  get '/search',  to: 'items#search'
  root to: 'items#index'
#carts controller
  get '/cart', to: 'carts#index'
  # post '/items/:id/cart', to: 'carts#add'   #下に移動してあります！！！！！！！！
  post '/cart', to: 'carts#add'
  patch '/cart/:id', to: 'carts#update'
  delete '/cart.:id', to: 'carts#remove'
  delete '/carts', to: 'carts#destroy'
#reviews controller
resources :reviews, only:[:edit, :update, :destroy]
resources :items, only:[:show] do
  resources :reviews, only:[:new, :create]
end
  # get '/items/:id/reviews', to: 'reviews#new'
  # post '/items/:id/reviews', to: 'reviews#create'
#addresses controller
  resources :addresses, only:[:create, :update, :destroy, :change, :edit, :new]
  get '/address/change', to: 'addresses#change'
#contacts controller
  resources :contacts, only:[:create, :new]

namespace :admins do
#admins/orders controller
  get '/orders', to: 'orders#index'
  patch '/orders/:id', to: 'orders#change'
  get '/search',  to: 'orders#search'
  get '/sort/orders',  to: 'orders#sort'
#admins/items controller
  resources :items, only: [:index, :show, :edit, :update, :new, :create] do
      resources :arrivals, only:[:new, :create]
  end
  post '/items/artist/new', to: 'items#artist_create'
  post '/items/label/new', to: 'items#label_create'
  post '/items/genre/new', to: 'items#genre_create'
  get '/items/edit/search', to: 'items#edit_search'
  get '/artist/:id/edit', to: 'items#artist_edit', as: "artist_edit"
  get '/label/:id/edit', to: 'items#label_edit', as: "label_edit"
  get '/genre/:id/edit', to: 'items#genre_edit', as: "genre_edit"
  patch '/artist/:id/update', to: 'items#artist_update', as: "artist_update"
  patch '/label/:id/update', to: 'items#label_update', as: "label_update"
  patch '/genre/:id/update', to: 'items#genre_update', as: "genre_update"
  patch '/status/:id', to: 'items#status', as: "status"
  patch '/items/:id', to: 'items#change'
  get  '/search/items', to: 'items#search'
  get '/sort/items',  to: 'items#sort'
#admins/arrivals controller
  resources :arrivals, only:[:index, :edit, :update, :destroy]
  get '/search/arrivals',  to: 'arrivals#search'
  get '/sort/arrivals',  to: 'arrivals#sort'
  # post '/items/:id/arrivals', to: 'arrivals#create'   #admins/items controllerに移動してます。
#admins/users controller
  resources :users, only:[:index, :show, :edit, :update, :destroy]
  get '/search/users',  to: 'users#search'
  patch '/withdraw/:id',  to: 'users#withdraw', as: "withdraw"
  #patch '/uesrs', to: 'users#change'
#admins/reviews controller
  resources :reviews, only:[:index, :show, :edit, :update, :destroy]
  post '/search/reviews',  to: 'reviews#search'
  get '/sort/reviews',  to: 'reviews#sort'
#admins/contacts controller
  resources :contacts, only:[:index, :show, :create]
  get '/contacts/new', to: 'contacts#new'
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses
  has_many :carts
  has_many :items, through: :carts
  has_many :orders
  has_many :order_items, through: :orders
  has_many :reviews

  ratyrate_rater

  def self.find_first_by_auth_conditions(warden_conditions)  #マイページ、レビューリンクようのインスタンスメソッド
    User.where(:email => warden_conditions[:email],:delete_flag=>0).first
  end

  validates :name_family_kanji, presence: true
  validates :name_first_kanji, presence: true
  VALID_NAME_FURIGANA_REGEX = /\A[ァ-ヶー－]+\z/
  validates :name_family_furigana, presence: true, format: { with: VALID_NAME_FURIGANA_REGEX }
  validates :name_first_furigana, presence: true, format: { with: VALID_NAME_FURIGANA_REGEX }
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address_prefecture, presence: true
  validates :address_city, presence: true
  validates :address_number, presence: true
  validates :phone_number, presence: true
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
    layout "admins"
    before_action :authenticate_admin!
	def index
	  @users = User.all
	end

	def search
		if params[:search_flag] == "1"
	  		@users = User.where("id LIKE ?", "#{params[:search_word]}")
		elsif params[:search_flag] == "2"
			@users = User.where("name_family_kanji || name_first_kanji LIKE ?", "%#{params[:search_word]}%")
		else params[:search_flag] == "3"
			@users = User.where("name_family_furigana || name_first_furigana LIKE ?", "%#{params[:search_word]}%")
		end
		render :index
	end

	def show
		@user = User.find(params[:id])
	end

	def withdraw
		user = User.find(params[:id])
		user.update(delete_flag: 1)
		flash[:notice] = "ユーザ情報の更新が完了しました。"
		redirect_to admins_user_path(user)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if  @user.update(user_params)
			flash[:notice] = "ユーザ情報の更新が完了しました。"
			redirect_to admins_user_path(@user)
	    else
	    	flash[:notice] = "error"
	    	render :edit
	    end
	end

	private
    def user_params
        params.require(:user).permit(:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  #protect_from_forgery with: :exception
  # before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  #   @address = Address.new(address_params)
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    resource.delete_flag = 1
    resource.save
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    redirect_to users_unsubscribe_complete_path
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  def unsubscribe
  end

  def complete
  end
  #ユーザ情報編集後の処理。お届け先情報書き換えとリダイレクト先指定
  def after_update_path_for(resource)
    @user = current_user
    @address = Address.where(user_id: @user.id).first  #ユーザIDに紐づいたお届け先情報の先頭(ユーザのお届け先)
    @address.update(
      user_id: current_user.id,
      delivery_name_family_kanji: @user.name_family_kanji,
      delivery_name_first_kanji: @user.name_first_kanji,
      delivery_name_family_furigana: @user.name_family_furigana,
      delivery_name_first_furigana: @user.name_first_furigana,
      delivery_postal_code: @user.postal_code,
      delivery_address_prefecture: @user.address_prefecture,
      delivery_address_city: @user.address_city,
      delivery_address_number: @user.address_number,
      delivery_address_building: @user.address_building
      )
    mypage_path
  end
  #新規登録後の処理。お届け先テーブルに保存とリダイレクト先指定。
  def after_sign_up_path_for(resource)
      @user = current_user
      Address.create(   #create = newとsaveを同時に行う
      user_id: @user.id,    #ユーザIDを保存
      delivery_name_family_kanji: @user.name_family_kanji,
      delivery_name_first_kanji: @user.name_first_kanji,
      delivery_name_family_furigana: @user.name_family_furigana,
      delivery_name_first_furigana: @user.name_first_furigana,
      delivery_postal_code: @user.postal_code,
      delivery_address_prefecture: @user.address_prefecture,
      delivery_address_city: @user.address_city,
      delivery_address_number: @user.address_number,
      delivery_address_building: @user.address_building
      )
    root_path
  end

  protected
  #新規登録、エディットのストロングパラメータ。オーバーライドしている
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag])
    # params.require(:address).permit(:delivery_name_family_kanji, :delivery_name_first_kanji, :delivery_name_family_furigana, :delivery_name_first_furigana, :delivery_postal_code, :delivery_address_prefecture, :delivery_address_city, :delivery_address_number, :delivery_address_building)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag])
  end
  #↓Devise情報編集P、パスワード確認が不要になる
  # def update_resource(resource, params)
  #   resource.update_without_current_password(params)
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # protected
  #   def configure_permitted_parameters
  #     devise_parameter_sanitizer.permit(:sign_up, keys: [:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag])
  #     devise_parameter_sanitizer.permit(:sign_in, keys: [:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag])
  #     devise_parameter_sanitizer.permit(:account_update, keys: [:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag])
  #   end
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #     super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


  # def after_sign_in_path_for(resource)
  #    user = current_user
  #    if user.delete_flag == 0
  #       root_path
  #    else
  #      　Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
  #       root_path
  #    end
  #  end

  def after_sign_out_path_for(resource)
   root_path
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
	  @user = current_user
	  @addresses = Address.where(user_id: @user)
	  @orders = @user.orders
	end

	def retire
	  user = current_user
	  user.update(delete_flag: 1)
	  Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
	  redirect_to users_unsubscribe_complete_path
	end
end

app/views/users/show.html.erb
<div class="jumbotron mypage-box">
<div class="mypage_title container">
	<h2 class="c1-2exam5">
		こんにちは
		<span style="font-weight: bold;">
			<%= @user.name_family_kanji %>  <%= @user.name_first_kanji %>
		</span>
		様
	</h2>
</div>
<div class="info_container container">
	<!--ユーザ情報-->
	<h3 class="mypage-title">お客様情報</h3>
	<table class="table table-bordered">
		<tr>
			<td class="active">氏名</td>
			<td><%= @user.name_family_kanji %>  <%= @user.name_first_kanji %></td>
		</tr>
		<tr>
			<td class="active">氏名（フリガナ）</td>
			<td><%= @user.name_family_furigana %>  <%= @user.name_first_furigana %></td>
		</tr>
		<tr>
			<td class="active">メールアドレス</td>
			<td><%= @user.email %></td>
		</tr>
		<tr>
			<td class="active">パスワード</td>
			<td><%= @user.password %></td>
		</tr>
		<tr>
			<td class="active">ご住所</td>
			<td>〒<%= @user.postal_code.insert(3, "-") %>  <%= @user.address_prefecture %>
				<%= @user.address_city %><%= @user.address_number %>
				<%= @user.address_building %>
			</td>
		</tr>
		<tr>
			<td class="active">お電話番号</td>
			<td><%= @user.phone_number %></td>
		</tr>
	</table>

	<div class="row">
		<%= link_to "お客様情報の編集", edit_user_registration_path(@user), class:"btn btn-success col-md-3 col-md-offset-9" %>
	</div>

	<div>
	<!--お届け先情報 -->
		<h3 class="mypage-title">お届け先情報</h3>
		<div class="row">
			<%= link_to "お届け先情報追加", new_address_path, class:"btn btn-primary col-md-3" %>
		</div></br>
	</div>
	<% @addresses.each.with_index(1) do |address,i| %>
	<div style="display:inline-block; font-weight: bold; font-size: 20px;">
		<%= i %>
	</div>
	<table class="table table-bordered">
		<tr>
			<td class="active">氏名</td>
			<td><%= address.delivery_name_family_kanji %>  <%= address.delivery_name_first_kanji %></td>
		</tr>
		<tr>
			<td class="active">氏名（フリガナ）</td>
			<td><%= address.delivery_name_family_furigana %>  <%= address.delivery_name_first_furigana %></td>
		</tr>
		<tr>
			<td class="active">ご住所</td>
			<td>
				<div style="float: left">
					〒<%= address.delivery_postal_code.insert(3, "-") %>
				</div>
				<div style="float: left, margin-left:5px">
					<%= address.delivery_address_prefecture %><%= address.delivery_address_city %><%= address.delivery_address_number %><%= address.delivery_address_building %>
				</div>
			</td>
		</tr>

	</table>
	<div class="row">
		<%= link_to "お届け先情報#{i}の編集", edit_address_path(address), class:"btn btn-success col-md-3 col-md-offset-9" %>
	</div>
	<% end %>
		<!--- 購入履歴 -->
		<h3 class="mypage-title">購入履歴</h3>
		<% @orders.each do |order| %>
		<div style="border-bottom:double 10px;">
			<div>
				<%= order.created_at.strftime('%Y/%m/%d') %>
                <% if order.order_status == 0 %>
                    <p class="text-danger">受付中</p>
                <% elsif order.order_status == 1 %>
                    <p class="text-warning">発送準備中</p>
                <% else %>
                    <p class="text-success">発送済み</p>
                <% end %>

			</div>
			<!--購入履歴・商品情報-->
			<% order.order_items.each do |oi| %>
			<div style="border:ridge;">
				<div class="clearfix">
					<span style="float:left;">
						<%= attachment_image_tag oi.item, :item_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60' %>
					</span>
						<span style="float:left;">
							商品名：<%= oi.item.item_name %>
						</span>
						</br>
					<span>
						アーティスト名：<%= oi.item.artist.artist_name %>
					</span>
					</br>
					<span style="float:left; font-weight:bold;">
						<% review = Review.reviewed_by(current_user,oi.item)
							if review.present? %>
							<%= link_to "レビュー編集", edit_review_path(review) %>
						<% else %>
							<%= link_to "レビューする", new_item_review_path(oi.item) %>
						<% end %>
					</span>
				</div>
				<div>
					価格：<%= oi.order_price.to_s(:delimited, delimiter: ',') %>円(税込)
				</div>
					購入数：<%= oi.order_number %>枚
			</div>
			<% end %>
			<!--購入履歴・宛先、料金-->
			<div>
				<%= "送付先：" + order.delivery_name_family_kanji %><%= order.delivery_name_first_kanji + "　様宛" %>
			</div>
				<%= "　　　　" + order.delivery_address_prefecture %><%= order.delivery_address_city %><%= order.delivery_address_number %><%= order.delivery_address_building %>
			<div>
			</div>
			<div class="clearfix">
				<span style="float:right;">
					送料:<%= order.postage %>   円(税込)
				</span>
			</div>
			<div class="clearfix">
				<span style="float:right;">
					合計：<%= (order.total_fee + order.postage).to_s(:delimited, delimiter: ',') %>円(税込)
				</span>
			</div>
		</div></br>
		<% end %>
	<div class="row" style="margin-top: 10px;">
		<%= link_to "退会手続きへ", users_unsubscribe_path(@user), class:"btn btn-danger col-md-offset-10" %>
	</div>
</div>
</div>

app/views/users/test.html.erb
<div class="white-box">
<div class="mypage_title container">
	<h1 class="c1-2exam5">こんにちは  <%= @user.name_family_kanji %>  <%= @user.name_first_kanji %>  様</h1>
</div>
<div class="info_container">
	<h3>お客様情報</h3>
	<table class="table table-bordered">
		<tr>
			<td>氏名</td>
			<td><%= @user.name_family_kanji %>  <%= @user.name_first_kanji %></td>
		</tr>
		<tr>
			<td>氏名（フリガナ）</td>
			<td><%= @user.name_family_furigana %>  <%= @user.name_first_furigana %></td>
		</tr>
		<tr>
			<td>メールアドレス</td>
			<td><%= @user.email %></td>
		</tr>
		<tr>
			<td>パスワード</td>
			<td><%= @user.password %></td>
		</tr>
		<tr>
			<td>ご住所</td>
			<td>〒<%= @user.postal_code.insert(3, "-") %>  <%= @user.address_prefecture %>
				<%= @user.address_city %><%= @user.address_number %>
				<%= @user.address_building %>
			</td>
		</tr>
		<tr>
			<td>お電話番号</td>
			<td><%= @user.phone_number %></td>
		</tr>
	</table>

	<h3>その他のお届け先</h3>
	<% @addresses.each.with_index(1) do |address,i| %>
	<%= i %>
	<table class="table table-bordered">
		<tr>
			<td>氏名</td>
			<td><%= address.delivery_name_family_kanji %>  <%= address.delivery_name_first_kanji %></td>
		</tr>
		<tr>
			<td>氏名（フリガナ）</td>
			<td><%= address.delivery_name_family_furigana %>  <%= address.delivery_name_first_furigana %></td>
		</tr>
		<tr>
			<td>ご住所</td>
			<td>〒<%= address.delivery_postal_code.insert(3, "-") %>  <%= address.delivery_address_prefecture %><%= address.delivery_address_city %><%= address.delivery_address_number %><%= address.delivery_address_building %></td>
		</tr>

	</table>
	<% end %>
	<h3>購入履歴</h3>
	<% @orders.each do |order| %>
		<div><%= order.created_at.strftime('%Y/%m/%d') %>  <%= order.order_status %></div>

			<% @order.each do || %>
				<%= oi.item.item_image_id %>
			<% end %>

		<div><p>送付先：<%= order.delivery_name_family_kanji %><%= order.delivery_name_first_kanji %>   様宛       <%= order.delivery_address_prefecture %><%= order.delivery_address_city %><%= order.delivery_address_number %><%= order.delivery_address_building %></p></div>
		<div>送料:<%= order.postage %>   円</div>
		<div>決済方法：◯○決済             合計：<%= order.total_fee %>円</div>
	<% end %>
</div>