config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#users controller
  get '/mypage', to: 'users#show'
  patch '/users', to: 'users#change'
  patch '/retire', to: 'users#retire',as: 'retire'
#users/registrations controller
  devise_scope :user do
    # get "sign_up", :to => "users/registrations#new"
    # get "sign_in", :to => "users/sessions#new"
    # get "sign_out", :to => "users/registrations#destroy"
    get 'users/unsubscribe', to: 'users/registrations#unsubscribe'
    get 'users/unsubscribe/complete', to: 'users/registrations#complete'
  end
#orders controller
  get '/order', to: 'orders#order'
  post '/order/confirmation', to: 'orders#confirmation'
  put '/order/confirmation', to: 'orders#create'
  post '/order', to: 'orders#create'
  get '/order/complete', to: 'orders#complete'
#items controller
  # resources :items, only:[:show]  #reviews controllerに移動してあります！！！！！！！！！
  get '/search',  to: 'items#search'
  root to: 'items#index'
#carts controller
  get '/cart', to: 'carts#index'
  # post '/items/:id/cart', to: 'carts#add'   #下に移動してあります！！！！！！！！
  post '/cart', to: 'carts#add'
  patch '/cart/:id', to: 'carts#update'
  delete '/cart.:id', to: 'carts#remove'
  delete '/carts', to: 'carts#destroy'
#reviews controller
resources :reviews, only:[:edit, :update, :destroy]
resources :items, only:[:show] do
  resources :reviews, only:[:new, :create]
end
  # get '/items/:id/reviews', to: 'reviews#new'
  # post '/items/:id/reviews', to: 'reviews#create'
#addresses controller
  resources :addresses, only:[:create, :update, :destroy, :change, :edit, :new]
  get '/address/change', to: 'addresses#change'
#contacts controller
  resources :contacts, only:[:create, :new]

namespace :admins do
#admins/orders controller
  get '/orders', to: 'orders#index'
  patch '/orders/:id', to: 'orders#change'
  get '/search',  to: 'orders#search'
  get '/sort/orders',  to: 'orders#sort'
#admins/items controller
  resources :items, only: [:index, :show, :edit, :update, :new, :create] do
      resources :arrivals, only:[:new, :create]
  end
  post '/items/artist/new', to: 'items#artist_create'
  post '/items/label/new', to: 'items#label_create'
  post '/items/genre/new', to: 'items#genre_create'
  get '/items/edit/search', to: 'items#edit_search'
  get '/artist/:id/edit', to: 'items#artist_edit', as: "artist_edit"
  get '/label/:id/edit', to: 'items#label_edit', as: "label_edit"
  get '/genre/:id/edit', to: 'items#genre_edit', as: "genre_edit"
  patch '/artist/:id/update', to: 'items#artist_update', as: "artist_update"
  patch '/label/:id/update', to: 'items#label_update', as: "label_update"
  patch '/genre/:id/update', to: 'items#genre_update', as: "genre_update"
  patch '/status/:id', to: 'items#status', as: "status"
  patch '/items/:id', to: 'items#change'
  get  '/search/items', to: 'items#search'
  get '/sort/items',  to: 'items#sort'
#admins/arrivals controller
  resources :arrivals, only:[:index, :edit, :update, :destroy]
  get '/search/arrivals',  to: 'arrivals#search'
  get '/sort/arrivals',  to: 'arrivals#sort'
  # post '/items/:id/arrivals', to: 'arrivals#create'   #admins/items controllerに移動してます。
#admins/users controller
  resources :users, only:[:index, :show, :edit, :update, :destroy]
  get '/search/users',  to: 'users#search'
  patch '/withdraw/:id',  to: 'users#withdraw', as: "withdraw"
  #patch '/uesrs', to: 'users#change'
#admins/reviews controller
  resources :reviews, only:[:index, :show, :edit, :update, :destroy]
  post '/search/reviews',  to: 'reviews#search'
  get '/sort/reviews',  to: 'reviews#sort'
#admins/contacts controller
  resources :contacts, only:[:index, :show, :create]
  get '/contacts/new', to: 'contacts#new'
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :addresses
  has_many :carts
  has_many :items, through: :carts
  has_many :orders
  has_many :order_items, through: :orders
  has_many :reviews

  ratyrate_rater

  def self.find_first_by_auth_conditions(warden_conditions)  #マイページ、レビューリンクようのインスタンスメソッド
    User.where(:email => warden_conditions[:email],:delete_flag=>0).first
  end

  validates :name_family_kanji, presence: true
  validates :name_first_kanji, presence: true
  VALID_NAME_FURIGANA_REGEX = /\A[ァ-ヶー－]+\z/
  validates :name_family_furigana, presence: true, format: { with: VALID_NAME_FURIGANA_REGEX }
  validates :name_first_furigana, presence: true, format: { with: VALID_NAME_FURIGANA_REGEX }
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address_prefecture, presence: true
  validates :address_city, presence: true
  validates :address_number, presence: true
  validates :phone_number, presence: true
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
    layout "admins"
    before_action :authenticate_admin!
	def index
	  @users = User.all
	end

	def search
		if params[:search_flag] == "1"
	  		@users = User.where("id LIKE ?", "#{params[:search_word]}")
		elsif params[:search_flag] == "2"
			@users = User.where("name_family_kanji || name_first_kanji LIKE ?", "%#{params[:search_word]}%")
		else params[:search_flag] == "3"
			@users = User.where("name_family_furigana || name_first_furigana LIKE ?", "%#{params[:search_word]}%")
		end
		render :index
	end

	def show
		@user = User.find(params[:id])
	end

	def withdraw
		user = User.find(params[:id])
		user.update(delete_flag: 1)
		flash[:notice] = "ユーザ情報の更新が完了しました。"
		redirect_to admins_user_path(user)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if  @user.update(user_params)
			flash[:notice] = "ユーザ情報の更新が完了しました。"
			redirect_to admins_user_path(@user)
	    else
	    	flash[:notice] = "error"
	    	render :edit
	    end
	end

	private
    def user_params
        params.require(:user).permit(:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  #protect_from_forgery with: :exception
  # before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  #   @address = Address.new(address_params)
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    resource.delete_flag = 1
    resource.save
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    redirect_to users_unsubscribe_complete_path
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  def unsubscribe
  end

  def complete
  end
  #ユーザ情報編集後の処理。お届け先情報書き換えとリダイレクト先指定
  def after_update_path_for(resource)
    @user = current_user
    @address = Address.where(user_id: @user.id).first  #ユーザIDに紐づいたお届け先情報の先頭(ユーザのお届け先)
    @address.update(
      user_id: current_user.id,
      delivery_name_family_kanji: @user.name_family_kanji,
      delivery_name_first_kanji: @user.name_first_kanji,
      delivery_name_family_furigana: @user.name_family_furigana,
      delivery_name_first_furigana: @user.name_first_furigana,
      delivery_postal_code: @user.postal_code,
      delivery_address_prefecture: @user.address_prefecture,
      delivery_address_city: @user.address_city,
      delivery_address_number: @user.address_number,
      delivery_address_building: @user.address_building
      )
    mypage_path
  end
  #新規登録後の処理。お届け先テーブルに保存とリダイレクト先指定。
  def after_sign_up_path_for(resource)
      @user = current_user
      Address.create(   #create = newとsaveを同時に行う
      user_id: @user.id,    #ユーザIDを保存
      delivery_name_family_kanji: @user.name_family_kanji,
      delivery_name_first_kanji: @user.name_first_kanji,
      delivery_name_family_furigana: @user.name_family_furigana,
      delivery_name_first_furigana: @user.name_first_furigana,
      delivery_postal_code: @user.postal_code,
      delivery_address_prefecture: @user.address_prefecture,
      delivery_address_city: @user.address_city,
      delivery_address_number: @user.address_number,
      delivery_address_building: @user.address_building
      )
    root_path
  end

  protected
  #新規登録、エディットのストロングパラメータ。オーバーライドしている
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag])
    # params.require(:address).permit(:delivery_name_family_kanji, :delivery_name_first_kanji, :delivery_name_family_furigana, :delivery_name_first_furigana, :delivery_postal_code, :delivery_address_prefecture, :delivery_address_city, :delivery_address_number, :delivery_address_building)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag])
  end
  #↓Devise情報編集P、パスワード確認が不要になる
  # def update_resource(resource, params)
  #   resource.update_without_current_password(params)
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # protected
  #   def configure_permitted_parameters
  #     devise_parameter_sanitizer.permit(:sign_up, keys: [:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag])
  #     devise_parameter_sanitizer.permit(:sign_in, keys: [:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag])
  #     devise_parameter_sanitizer.permit(:account_update, keys: [:name_family_kanji, :name_first_kanji, :name_family_furigana, :name_first_furigana, :postal_code, :address_prefecture, :address_city, :address_number, :address_building, :phone_number, :delete_flag])
  #   end
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #     super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


  # def after_sign_in_path_for(resource)
  #    user = current_user
  #    if user.delete_flag == 0
  #       root_path
  #    else
  #      　Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
  #       root_path
  #    end
  #  end

  def after_sign_out_path_for(resource)
   root_path
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
	  @user = current_user
	  @addresses = Address.where(user_id: @user)
	  @orders = @user.orders
	end

	def retire
	  user = current_user
	  user.update(delete_flag: 1)
	  Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
	  redirect_to users_unsubscribe_complete_path
	end
end

app/views/admins/users/edit.html.erb
<%= stylesheet_link_tag "admins/users", :media => "all" %>

<div class="signin_container container">
<h2>顧客情報の編集 </h2>

<%= form_for @user, url:admins_user_path(@user) do |f| %>

    <div class="name_kanji field">
      <div class="field">
        <%= f.label :"氏名　　　　　　　　　姓" %>
        <%= f.text_field :name_family_kanji, autofocus: true  %>
        <%= f.label :"　　名" %>
        <%= f.text_field :name_first_kanji, autofocus: true  %>
      </div>
    </div>

    <div class="name_furigana line">
      <div class="field">
        <%= f.label :"氏名（フリガナ）　　セイ" %>
        <%= f.text_field :name_family_furigana, autofocus: true  %>
        <%= f.label :"　メイ" %>
        <%= f.text_field :name_first_furigana, autofocus: true  %>
      </div>
    </div>

    <div class="email line">
      <div class="field">
        <%= f.label :"メールアドレス　　　　　" %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

    <div class="postal_code line">
      <div class="field">
        <%= f.label :"郵便番号　　　　　　　　" %>
        <%= f.text_field :postal_code, autofocus: true  %>
      </div>
    </div>

    <div class="address_prefecture line">
      <div class="field">
        <%= f.label :"都道府県　　　　　　　　" %>
        <%= f.text_field :address_prefecture, autofocus: true  %>
      </div>
    </div>

    <div class="address_city line">
      <div class="field">
        <%= f.label :"住所１（市区町村）　　　" %>
        <%= f.text_field :address_city, autofocus: true  %>
      </div>
    </div>

    <div class="address_number line">
      <div class="field">
        <%= f.label :"住所２（番地）　　　　　" %>
        <%= f.text_field :address_number, autofocus: true  %>
      </div>
    </div>

    <div class="address_building line">
      <div class="field">
        <%= f.label :"住所３（建物名）　　　　" %>
        <%= f.text_field :address_building, autofocus: true  %>
      </div>
    </div>

    <div class="phone_number line">
      <div class="field">
        <%= f.label :"お電話番号　　　　　　　" %>
        <%= f.text_field :phone_number, autofocus: true  %>
        <%= f.hidden_field :delete_flag, :value => 0 %>
      </div>
    </div>
  <% if @user.delete_flag == 0 %>
  <div class="actions">
      <%= f.submit "更新", class:"btn btn-primary" %>
  </div>
  <% else %>
    <div class="actions">
      <%= f.submit "更新して登録状態に戻す", class:"btn btn-primary" %>
  </div>
  <% end %>
<% end %>


<%= link_to "戻る", admins_user_path(@user), class:"btn btn-info" %>
</div>

app/views/admins/users/index.html.erb
<%= stylesheet_link_tag "admins/users", :media => "all" %>
<div class="a_users_container">
	<h1>顧客情報一覧</h1>
<!-- 	<div style="color:red;">
		<%= notice %>
	</div><br> -->
	<div class="search-content">
		<%= form_tag(admins_search_users_path, method: :get) do %>
			<%= radio_button_tag :search_flag, 1, checked: true %>顧客ID
			<%= radio_button_tag :search_flag, 2 %>顧客(漢字)
			<%= radio_button_tag :search_flag, 3 %>顧客(フリガナ)
			<%= text_field_tag :search_word %>
			<%= submit_tag "検索" %>
		<% end %>
	</div><br>
	<table class="table table-bordered" >
		<tr class="active">
	    	<th>顧客ID</th>
	    	<th>顧客名</th>
	    	<th>フリガナ</th>
	    	<th>メールアドレス</th>
	    	<th>会員ステータス</th>
		</tr>
		<% @users.each do |u| %>
		<tr>
	    	<td>
	    		<div>
	    			<%= link_to u.id, admins_user_path(u.id),class: "btn-square-slant"  %>
	    		</div>
	    	</td>
	    	<td><%= u.name_family_kanji + u.name_first_kanji %></td>
	    	<td><%= u.name_family_furigana + u.name_first_furigana %></td>
	    	<td><%= u.email %></td>
	    	<% if u.delete_flag == 0 %>
	    		<td class="bg-success">登録中</td>
	    		<% else %>
	    		<td class="bg-danger">退会</td>
	    		<% end %>
		</tr>
	  	<% end %>
	</table>
</div>

app/views/admins/users/show.html.erb
<%= stylesheet_link_tag "admins/users", :media => "all" %>

<div class="a_users_container">
	<h1 style="padding-bottom:20px;">顧客情報詳細</h1>
	<div style="color:red;">
		<%= flash[:notice] %>
	</div><br>
		<table class="table table-bordered">
		<tr>
			<td class="active">会員ステータス</td>
				<% if @user.delete_flag == 0 %>
				<td class="bg-success">登録中</td>
					<% else %>
					<td class="bg-danger">退会</td>
				<% end %>
		</tr>
		<tr>
			<td class="active">顧客ID</td>
			<td><%= @user.id %></td>
		</tr>
		<tr>
			<td class="active">氏名</td>
			<td><%= @user.name_family_kanji %>  <%= @user.name_first_kanji %></td>
		</tr>
		<tr>
			<td class="active">氏名（フリガナ）</td>
			<td><%= @user.name_family_furigana %>  <%= @user.name_first_furigana %></td>
		</tr>
		<tr>
			<td class="active">メールアドレス</td>
			<td><%= @user.email %></td>
		</tr>
		<tr>
			<td class="active">パスワード</td>
			<td><%= @user.password %></td>
		</tr>
		<tr>
			<td class="active">ご住所</td>
			<td>〒<%= @user.postal_code.insert(3, "-") %>  <%= @user.address_prefecture %>
				<%= @user.address_city %><%= @user.address_number %>
				<%= @user.address_building %>
			</td>
		</tr>
		<tr>
			<td class="active">お電話番号</td>
			<td><%= @user.phone_number %></td>
		</tr>
	</table>
	<div class="container">
		<div class="row">
			<%= link_to "登録情報編集", edit_admins_user_path(@user), class:"btn btn-success col-md-2 col-md-offset-4" %>
		</div>
		<div class="row">
			<%= link_to "顧客一覧へ", admins_users_path, class:"btn btn-info col-md-2 col-md-offset-4" %>
		</div>
		<% if @user.delete_flag == 0 %>
		<div class="row">
			<%= link_to "会員情報削除", admins_withdraw_path(@user), method: :patch, class:"btn btn-danger col-md-2 col-md-offset-4", "data-confirm" => "本当に削除しますか？この操作は取り消せません。" %>
		</div>
		<% end %>
	</div>


</div>