config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#users controller
  get '/mypage', to: 'users#show'
  patch '/users', to: 'users#change'
  patch '/retire', to: 'users#retire',as: 'retire'
#users/registrations controller
  devise_scope :user do
    # get "sign_up", :to => "users/registrations#new"
    # get "sign_in", :to => "users/sessions#new"
    # get "sign_out", :to => "users/registrations#destroy"
    get 'users/unsubscribe', to: 'users/registrations#unsubscribe'
    get 'users/unsubscribe/complete', to: 'users/registrations#complete'
  end
#orders controller
  get '/order', to: 'orders#order'
  post '/order/confirmation', to: 'orders#confirmation'
  put '/order/confirmation', to: 'orders#create'
  post '/order', to: 'orders#create'
  get '/order/complete', to: 'orders#complete'
#items controller
  # resources :items, only:[:show]  #reviews controllerに移動してあります！！！！！！！！！
  get '/search',  to: 'items#search'
  root to: 'items#index'
#carts controller
  get '/cart', to: 'carts#index'
  # post '/items/:id/cart', to: 'carts#add'   #下に移動してあります！！！！！！！！
  post '/cart', to: 'carts#add'
  patch '/cart/:id', to: 'carts#update'
  delete '/cart.:id', to: 'carts#remove'
  delete '/carts', to: 'carts#destroy'
#reviews controller
resources :reviews, only:[:edit, :update, :destroy]
resources :items, only:[:show] do
  resources :reviews, only:[:new, :create]
end
  # get '/items/:id/reviews', to: 'reviews#new'
  # post '/items/:id/reviews', to: 'reviews#create'
#addresses controller
  resources :addresses, only:[:create, :update, :destroy, :change, :edit, :new]
  get '/address/change', to: 'addresses#change'
#contacts controller
  resources :contacts, only:[:create, :new]

namespace :admins do
#admins/orders controller
  get '/orders', to: 'orders#index'
  patch '/orders/:id', to: 'orders#change'
  get '/search',  to: 'orders#search'
  get '/sort/orders',  to: 'orders#sort'
#admins/items controller
  resources :items, only: [:index, :show, :edit, :update, :new, :create] do
      resources :arrivals, only:[:new, :create]
  end
  post '/items/artist/new', to: 'items#artist_create'
  post '/items/label/new', to: 'items#label_create'
  post '/items/genre/new', to: 'items#genre_create'
  get '/items/edit/search', to: 'items#edit_search'
  get '/artist/:id/edit', to: 'items#artist_edit', as: "artist_edit"
  get '/label/:id/edit', to: 'items#label_edit', as: "label_edit"
  get '/genre/:id/edit', to: 'items#genre_edit', as: "genre_edit"
  patch '/artist/:id/update', to: 'items#artist_update', as: "artist_update"
  patch '/label/:id/update', to: 'items#label_update', as: "label_update"
  patch '/genre/:id/update', to: 'items#genre_update', as: "genre_update"
  patch '/status/:id', to: 'items#status', as: "status"
  patch '/items/:id', to: 'items#change'
  get  '/search/items', to: 'items#search'
  get '/sort/items',  to: 'items#sort'
#admins/arrivals controller
  resources :arrivals, only:[:index, :edit, :update, :destroy]
  get '/search/arrivals',  to: 'arrivals#search'
  get '/sort/arrivals',  to: 'arrivals#sort'
  # post '/items/:id/arrivals', to: 'arrivals#create'   #admins/items controllerに移動してます。
#admins/users controller
  resources :users, only:[:index, :show, :edit, :update, :destroy]
  get '/search/users',  to: 'users#search'
  patch '/withdraw/:id',  to: 'users#withdraw', as: "withdraw"
  #patch '/uesrs', to: 'users#change'
#admins/reviews controller
  resources :reviews, only:[:index, :show, :edit, :update, :destroy]
  post '/search/reviews',  to: 'reviews#search'
  get '/sort/reviews',  to: 'reviews#sort'
#admins/contacts controller
  resources :contacts, only:[:index, :show, :create]
  get '/contacts/new', to: 'contacts#new'
end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :discs, inverse_of: :item
  has_many :songs, through: :discs
#   accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :discs
  has_many :reviews
  has_many :carts
  has_many :users, through: :carts
  attachment :item_image
	belongs_to :artist
	belongs_to :label
	belongs_to :genre
	is_impressionable counter_cache: true
	has_many :order_items
	has_many :orders, through: :order_items
	has_many :arrivals, dependent: :destroy
	accepts_nested_attributes_for :arrivals
	enum item_delete_flag: { sales: 0, stop: 1 }
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
	layout "admins"

# protect_from_forgery except: :status
	before_action :authenticate_admin!
	def index
		@items = Item.all.order("id DESC").page(params[:page]).per(30)
		@sums = []
		@orderednumber = []
		@items.each do |item|
			@arrival_sums = Arrival.where(item_id: item.id).sum(:arrival_number)
			@order_items_sums = OrderItem.where(item_id: item.id).sum(:order_number)
			@sums << (@arrival_sums - @order_items_sums)
			@orderednumber << (item.order_items.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day).sum(:order_number))
		end
	end

	# def sort
	# 	# 在庫数
	# 	if params[:sort_type] == "1" && params[:sort_flag] == "1"
	# 		@items = Item.all.order('created_at ASC').page(params[:page]).per(2)
	# 		render :index
	# 	elsif params[:sort_type] == "1" && params[:sort_flag] == "2"
	# 		@reviews = Review.all.order('created_at DESC').page(params[:page]).per(2)
	# 		render :index
	# 	# 閲覧数
	# 	elsif params[:sort_type] == "2" && params[:sort_flag] == "1"
	# 		@reviews = Review.all.order('satisfaction ASC').page(params[:page]).per(2)
	# 		render :index
	# 	elsif params[:sort_type] == "2" && params[:sort_flag] == "2"
	# 		@reviews = Review.all.order('satisfaction DESC').page(params[:page]).per(2)
	# 		render :index
	# 	# 週間売り上げ枚数
	# 	elsif params[:sort_type] == "3" && params[:sort_flag] == "1"
	# 		@reviews = Review.all.order('satisfaction ASC').page(params[:page]).per(2)
	# 		render :index
	# 	elsif params[:sort_type] == "3" && params[:sort_flag] == "2"
	# 		@reviews = Review.all.order('satisfaction DESC').page(params[:page]).per(2)
	# 		render :index
	# 	end
	# end

	# def search
	# 	if params[:search_flag] == "1"
	# 		@artists = Artist.where("artist_name LIKE ?", "%#{params[:search_word]}%")
	# 		# binding.pry
	# 		@items = [] 								#配列の箱作成
	# 		@artists.each do |a|				#検索したアーティストを繰り返す
	# 			a.items.where(item_delete_flag: 0).each do |i|
	# 				@items << i
	# 			end
	# 		end
	# 	elsif params[:search_flag] == "2"
	# 		@items = Item.where("item_name LIKE ?", "%#{params[:search_word]}%")
	# 		@items = @items.reverse.uniq
	# 		@items = Kaminari.paginate_array(@items).page(params[:page]).per(3)
	# 	end
	# 	render :index

	def show
		@item = Item.find(params[:id])
		@arrival = Arrival.new
        @arrivals_sum =  Arrival.where(item_id: @item.id).sum(:arrival_number)
        @order_items_sum = OrderItem.where(item_id: @item.id).sum(:order_number)
        @arrivals = @item.arrivals.order('id desc')
		@arrivals = Kaminari.paginate_array(@arrivals).page(params[:page]).per(10)
        @order_items = @item.order_items.order('id desc')
        @order_items = Kaminari.paginate_array(@order_items).page(params[:page]).per(10)
        @reviews = @item.reviews.order('id desc')
        @reviews = Kaminari.paginate_array(@reviews).page(params[:page]).per(10)
	end

	def edit
		@item = Item.find(params[:id])
		# @disc = @item.discs
		# @song = @disc.songs
	end
	def status
		@item = Item.find(params[:id])
		if @item.item_delete_flag_before_type_cast == 0
			@item.update(item_delete_flag: 1)
    elsif @item.item_delete_flag_before_type_cast == 1
      @item.update(item_delete_flag: 0)
    end
	end

	def update
		@item = Item.find(params[:id])
		@artist = Artist.find(params[:artist][:id])
		@artist.update!(artist_params)
		@label = Label.find(params[:artist][:id])
		@label.update!(label_params)
		@genre = Genre.find(params[:artist][:id])
		@genre.update!(genre_params)
		params[:item][:disc].each do |key,disc|
			@disc = Disc.find(key.to_i)
			@disc.update!({
				disc_name: disc[:disc_name]
			})
			disc[:song].each do |key, song|
				@song = Song.find(key.to_i)
				@song.update!({
					song: song[:song]
				})
			end
		end
		# @disc.update!(disc_params)
		# @song = Song.find(params[:id])
		# @song.update!(song_params)
		if @item.update(item_params)
			flash[:notice] = "編集完了"
			redirect_to admins_item_path(@item.id)
		 else
			render :edit
		 end
	end

	def new
		@item = Item.new
		@item.arrivals.build
		@disc = @item.discs.build
		@song = @disc.songs.build
		@artists = Artist.all
		@labels = Label.all
		@genres = Genre.all
		@artist = Artist.new
		@label = Label.new
		@genre = Genre.new
	end
	def create
		item = Item.new(item_params)
		artist = Artist.where("artist_name = '#{params[:item][:artist_id]}'").first
		item.artist_id = artist.id
		label = Label.where("label_name = '#{params[:item][:label_id]}'").first
		item.label_id = label.id
		genre = Genre.where("genre_name = '#{params[:item][:genre_id]}'").first
		item.genre_id = genre.id
		item.save
		redirect_to new_admins_item_path
	end
	def artist_create
		artist = Artist.new(artist_params)
		artist.save
		redirect_to new_admins_item_path
	end
	def label_create
		label = Label.new(label_params)
		label.save
		redirect_to new_admins_item_path
	end
	def genre_create
		genre = Genre.new(genre_params)
		genre.save
		redirect_to new_admins_item_path
	end
	def edit_search
		if params[:search_flag] == "1"
			@artist_name = Artist.where("artist_name LIKE ?", "%#{params[:search_word]}%")
		elsif params[:search_flag] == "2"
			@label_name = Label.where("label_name LIKE ?", "%#{params[:search_word]}%")
		elsif params[:search_flag] == "3"
			@genre_name = Genre.where("genre_name LIKE ?", "%#{params[:search_word]}%")
		end
		@item = Item.new
		@item.arrivals.build
		@disc = @item.discs.build
		@song = @disc.songs.build
		@artists = Artist.all
		@labels = Label.all
		@genres = Genre.all
		@artist = Artist.new
		@label = Label.new
		@genre = Genre.new
		render :new
	end
	def artist_edit
		@artist = Artist.find(params[:id])
	end
	def label_edit
		@label = Label.find(params[:id])
	end
	def genre_edit
		@genre = Genre.find(params[:id])
	end
	def artist_update
        @artist = Artist.find(params[:id])
        @artist.update(artist_params)
		redirect_to new_admins_item_path
	end
	def label_update
        @label = Label.find(params[:id])
        @label.update(label_params)
		redirect_to new_admins_item_path
	end
	def genre_update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
		redirect_to new_admins_item_path
	end

private
	def item_params
		params.require(:item).permit(:item_name, :item_type, :item_image, :item_price, :artist_id, :label_id, :genre_id, :item_release_date, :item_delete_flag, arrivals_attributes: [:arrival_number, :arrival_date],  discs_attributes: [:id, :disc_name, :_destroy, songs_attributes: [:id, :song, :_destroy]])
	end
	def artist_params
		params.require(:artist).permit(:artist_name)
	end

	def label_params
		params.require(:label).permit(:label_name)
	end
	def genre_params
		params.require(:genre).permit(:genre_name)
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.page(params[:page]).where(item_delete_flag: 0).per(14).reverse_order
		@day = Date.today.strftime('%y/%m/%d')
		@week_ago = Date.today.ago(1.week).strftime('%y/%m/%d')
		@hash_sales_ranking = OrderItem.rank_sales_items
		@item_sales_key = @hash_sales_ranking.keys
		@item_sales_ranking = []
		@item_sales_key.each do |i|
			item  = Item.find(i)
			if item.item_delete_flag_before_type_cast == 0
				@item_sales_ranking << item
				if @item_sales_ranking.count == 5
					break
			    end
			end
		end
    	@hash_most_viewed_impression = Impression.where(created_at: 1.week.ago.beginning_of_day..Time.zone.now.end_of_day).limit(5).group(:impressionable_id).order('count_impressionable_id desc').count(:impressionable_id)
		@item_view_keys = @hash_most_viewed_impression.keys
		@item_view_ranking = []
		unless @item_view_keys[0].blank?
			@item_view_keys.each do |i|
				item  = Item.find(i)
				if item.item_delete_flag_before_type_cast == 0
					@item_view_ranking << item
				    if @item_view_ranking.count == 5
					   break
				    end
				end
			end
		end
	end
	# ApplicationControllerへ
	# def search
	# 	@hash_sales_ranking = OrderItem.rank_sales_items
	# 	@most_viewed = Item.order('impressions_count DESC').take(4)
	# 	if params[:search_flag] == "1"
	# 		@artists = Artist.where("artist_name LIKE ?", "%#{params[:search_word]}%")
	# 		@items = []
	# 		@artists.each do |a|
	# 			a.items.each do |i|
	# 				@items << i
	# 			end
	# 		end
	# 		@items = @items.reverse
	# 		@items = Kaminari.paginate_array(@items).page(params[:page]).per(3)
	# 		@day = Date.today.strftime('%y/%m/%d')
	# 		@week_ago = Date.today.ago(1.week).strftime('%y/%m/%d')
	# 	elsif params[:search_flag] == "2"
	# 		@items = Item.joins(discs: :songs).where("song LIKE ?", "%#{params[:search_word]}%")
	# 		@items = @items.reverse.uniq
	# 		@items = Kaminari.paginate_array(@items).page(params[:page]).per(3)
	# 		@day = Date.today.strftime('%y/%m/%d')
	# 		@week_ago = Date.today.ago(1.week).strftime('%y/%m/%d')
	# 	end
	# 	render :index
	# end
	def show
		@item = Item.find(params[:id])
		@users = User.where(delete_flag: 0)
		@reviews = []
		@users.each do |r|
			@reviews << Review.where(user_id: r.id, item_id: @item.id)
		end
	    impressionist(@item, nil)
	    @reviews = @reviews.flatten
	    @cart = Cart.new
        @satisfaction_average = @item.reviews.average(:satisfaction)
        @satisfaction_count = @item.reviews.length
        @reviews = Kaminari.paginate_array(@reviews).page(params[:page]).per(3)
        @arrivals_sum =  Arrival.where(item_id: @item.id).sum(:arrival_number)
        @order_items_sum = OrderItem.where(item_id: @item.id).sum(:order_number)
	end
end

app/views/admins/items/_disc_fields.html.erb
<div class="nested-fields well well-compact" style="width:285px; float:left">
  <div class="form-group">
    <%= f.text_field :disc_name %>
    <%= link_to_remove_association "ディスク削除", f %>
  </div>

  <div class="songs">
    <%= f.fields_for :songs do |song| %>
    <%= render 'song_fields', f: song %>
    <%end%>
    <div id="links">
    <%= link_to_add_association "曲追加", f, :songs %>
    </div>
  </div>
</div>

app/views/admins/items/_form.html.erb
<%= form_for(@item, url: admins_items_path) do |f| %>
    <div class="form_for_field">
        <p>シングル名/アルバム名：<%= f.text_field :item_name, :style=>"width: 400px;" %></p>
        <p> CDタイプ：<%= f.select :item_type, [["シングル", "シングル"], ["アルバム", "アルバム"],  ["EP", "EP"]], :style=>"width: 200px;" %>　アーティスト名：<%= f.text_field :artist_id, :style=>"width: 200px;", type:"search", autocomplete:"on", list:"keywords1" %></p>
        <p> レーベル名：<%= f.text_field :label_id, :style=>"width: 200px;", type:"search", autocomplete:"on", list:"keywords2" %> ジャンル名：<%= f.text_field :genre_id, :style=>"width: 200px;", type:"search", autocomplete:"on", list:"keywords3" %></p>
        <datalist id="keywords1">
          <%= @artists.all.each do |artist| %>
            <option value="<%= artist.artist_name %>"></option>
          <% end %>
        </datalist>
        <datalist id="keywords2">
          <%= @labels.all.each do |label| %>
            <option value="<%= label.label_name %>"></option>
          <% end %>
        </datalist>
        <datalist id="keywords3">
          <%= @genres.all.each do |genre| %>
            <option value="<%= genre.genre_name %>"></option>
          <% end %>
        </datalist>
        <p>価格(税別)：<%= f.text_field :item_price, :style=>"width: 100px;" %>円　発売日：<%= f.text_field :item_release_date, :style=>"width: 100px;" %>　販売ステータス：<%= f.select :item_delete_flag, [["販売中", "sales"], ["停止中", "stop"]] %></p>
        <p>ジャケット画像：<%= f.attachment_field :item_image %></p>
        <%= f.fields_for :arrivals do |a| %>
          <p>入荷数追加：<%= a.text_field :arrival_number, :style=>"width: 50px;" %>枚 入荷日：<%= a.text_field :arrival_date, :style=>"width: 100px;" %> <%= link_to "商品一覧へ戻る", admins_items_path, class: "btn btn-default", :style=>"background-color:yellow; margin-left: 120px;" %></p>
        <% end %>

    </div>
    <div class="clearfix">
        <h3>ディスク＆曲目</h3>
        <div id="discs">
            <%= f.fields_for :discs do |disc| %>
              <%= render 'disc_fields', f: disc %>
            <% end %>
        </div>
        <div id="links">
           <%= link_to_add_association '追加',f, :discs %>
        </div>
    </div>
    <div style="float: right; margin-left: 100px; width: 200px;"><%= f.submit '商品新規追加する', class: "btn btn-default", :style=>"background-color:red;" %>
    </div>
<% end %>

app/views/admins/items/_song_fields.html.erb
<div class="nested-fields form-inline">
  <div class="form-group">
	<%= f.text_field :song%>
	<%= link_to_remove_association "曲削除", f %>
  </div>
</div>

app/views/admins/items/artist_edit.html.erb
<%= form_for(@artist, url:admins_artist_update_path) do |a| %>
	アーティスト：<%= a.text_field :artist_name %>
	<%= a.submit '更新' %>
<% end %>

app/views/admins/items/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<div>
				<h1>商品新規追加</h1>
			</div>
			<%= render 'form', item: @item %>
		</div>
		<div class="col-md-4">
			<h1>新規登録</h1>
			<%= form_for(@artist, url:admins_items_artist_new_path) do |a| %>
				アーティスト：<%= a.text_field :artist_name %>
				<%= a.submit '追加' %>
		    <% end %>
		    <%= form_for(@label, url:admins_items_label_new_path) do |l| %>
				レーベル：<%= l.text_field :label_name %>
				<%= l.submit '追加' %>
		    <% end %>
		    <%= form_for(@genre, url:admins_items_genre_new_path) do |g| %>
				ジャンル：<%= g.text_field :genre_name %>
				<%= g.submit '追加' %>
			<% end %>
			<h1>編集</h1>
			<div class="edit-searth">
		    	<%= form_tag(admins_items_edit_search_path, method: :get) do %>
		    		<%= radio_button_tag :search_flag, 1, checked: true %>アーティスト
					<%= radio_button_tag :search_flag, 2 %>レーベル
					<%= radio_button_tag :search_flag, 3 %>ジャンル
					<%= text_field_tag :search_word %>
				<%= submit_tag "検索" %>
				<% end %>
			<% if @artist_name.present? %>
				<% @artist_name.each do |a| %>
					<p><%= a.id %>.<%= a.artist_name %><%= link_to "編集", admins_artist_edit_path(a.id) %></p>
				<% end %>
			<% elsif @label_name.present? %>
				<% @label_name.each do |l| %>
					<p><%= l.id %>.<%= l.label_name %><%= link_to "編集", admins_label_edit_path(l.id) %></p>
				<% end %>
			<% elsif @genre_name.present? %>
				<% @genre_name.each do |g| %>
					<P><%= g.id %>.<%= g.genre_name %><%= link_to "編集", admins_genre_edit_path(g.id) %></p>
				<% end %>
			<% end %>
		    </div>
		</div>
	</div>
</div>

app/views/admins/items/show.html.erb
<%= stylesheet_link_tag "admins/items", :media => "all" %>

<div class="container">
	<div class="row">
		<div class="col-md-7">
			<h2>商品詳細</h2>
			<div class="item-container-left">
				<%= attachment_image_tag @item, :item_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %>
				<p>タイプ: <%= @item.item_type %></p>
				<p>ジャンル: <%= @item.genre.genre_name %></p>
				<p>発売日: <%= @item.item_release_date.strftime('%y/%m/%d') %></p>
				<p>価格(別): <%= @item.item_price.to_s(:delimited, delimiter: ',') %>円</p>
				<p><%= link_to "編集する", edit_admins_item_path(@item.id), :style=>"background-color:yellow;" %></p>
				<p><%= link_to "商品一覧へ", admins_items_path, :style=>"background-color:yellow;" %></p>
			</div>
			<div class="item-container-right">
				<p>商品名: <%= @item.item_name %></p>
				<p>アーティスト名: <%= @item.artist.artist_name %></p>
				<p>レーベル名: <%= @item.label.label_name %></p>
				<P>曲名一覧</P>
				<% @item.discs.each do |d| %>
				<div class="disc-table">
					<p style="text-decoration: underline; font-size:15px;"><%= d.disc_name %></p>
					<div class="song-table">
					<% d.songs.each.with_index(1) do |s, i| %>
						<p><%= i %>.<%= s.song %></p>
					<% end %>
					</div>
				</div>
				<% end %>
			</div>
		</div>
		<div class="col-md-5">
			<h2>販売ステータス</h2>
			<% if @item.item_delete_flag_before_type_cast == 0 %>
			<%= link_to @item.item_delete_flag_i18n, admins_status_path(@item), method: :patch, remote: true, id:"status1", :style=>"font-size: 40px; color: black;" %>
			<% elsif @item.item_delete_flag_before_type_cast == 1 %>
			<%= link_to @item.item_delete_flag_i18n, admins_status_path(@item), method: :patch, remote: true, id:"status2", :style=>"font-size: 40px; color: white; background-color: red;" %>
			<% end %>
			<h2>入荷登録</h2>
			<%= form_for(@arrival, url: admins_item_arrivals_path(@item)) do |f| %>
			<p>在庫数：<%= @arrivals_sum - @order_items_sum %></p>
			<p>追加数：<%= f.text_field :arrival_number, :style=>"width: 50px;" %>枚</p>
			<p>入荷日：<%= f.text_field :arrival_date, :style=>"width: 100px;" %>(yyyy-mm-dd)</p>
			<%= f.hidden_field :item_id, value:@item.id %>
			<%= f.submit "入荷登録する", class:"btn btn-default", :style=>"background-color:yellow;" %>
			<% end %>
		</div>
	</div>

	<div class="row2">
		<div class="col-md-12">
		    <div class="wrap">
				<ul id="tab-menu">
					<li><a href="#tab1" class="active">入荷履歴</a></li>
					<li><a href="#tab2" class="">受注履歴</a></li>
					<li><a href="#tab3" class="">レビュー一覧</a></li>
				</ul>

		      	<div id="tab-contents" class="clearfix">
		        <div id="tab1" class="tab">
		          	<div class="containers">
						<table style="margin: 40px 50px 0 50px;">
							<tr style="background-color: #AFCDE4; ">
								<th>入荷ID</th>
			                	<th>入荷日</th>
			                	<th>枚数</th>
			                	<th></th>
			                	<th></th>
					    	</tr>
					    	<% @arrivals.each do |a| %>
							<tr style="border-bottom-style: ridge; border-color: #AFCDE4;">
			                	<th style="width: 200px;"><%= a.id %></th>
			                	<th style="width: 300px;"><%= a.arrival_date %></th>
			                	<th style="width: 200px;"><%= a.arrival_number %></th>
			                	<th style="width: 50px; background-color: yellow; text-align: center;"><%= link_to "編集", edit_admins_arrival_path(a.id) %></th>
			                	<th style="width: 50px; background-color: red; text-align: center;"><%= link_to "削除", admins_arrival_path(a.id), method: :delete, data: { confirm: "削除しますがよろしいですか?" }  %></th>
					    	</tr>
					    	<% end %>
					    </table>
					    <div class="pagenate"><%= paginate @arrivals %></div>
		      	  	</div>
		        </div>

		        <div id="tab2" class="tab">
		          	<div class="containers">
						<table style="margin: 40px 50px 0 50px;">
							<tr style="background-color: #D7D088; ">
								<th>受注ID</th>
			                	<th>受注日</th>
			                	<th>枚数</th>
			                	<th>受注ステータス</th>
					    	</tr>
					    	<% @order_items.each do |o| %>
							<tr style="border-bottom-style: ridge; border-color: #D7D088;">
			                	<th style="width: 200px;"><%= o.id %></th>
			                	<th style="width: 300px;"><%= o.created_at.strftime('%Y-%m-%d') %></th>
			                	<th style="width: 150px;"><%= o.order_number %></th>
			                	<% if o.order.order_status == 0 %>
			                	<th style="width: 150px; background-color: red; text-align: center;">受付</th>
			                	<% elsif o.order.order_status == 1 %>
			                	<th style="width: 150px; background-color: yellow; text-align: center;">準備中</th>
			                	<% else %>
			                	<th style="width: 150px; text-align: center;">出荷済</th>
			                	<% end %>
					    	</tr>
					    	<% end %>
					    </table>
					    <div class="pagenate"><%= paginate @order_items %></div>
		      	  	</div>
		        </div>

		        <div id="tab3" class="tab">
		          	<div class="containers">
						<table style="margin: 40px 50px 0 50px;">
							<tr style="background-color: #CFDF9F; ">
								<th>レビューID</th>
			                	<th>レビュー日</th>
			                	<th>ユーザ名</th>
			                	<th>満足度</th>
					    	</tr>
					    	<% @reviews.each do |r| %>
							<tr style="border-bottom-style: ridge; border-color: #CFDF9F;">
			                	<th style="width: 200px;"><%= link_to "#{r.id}", admins_review_path(r.id) %></th>
			                	<th style="width: 250px;"><%= r.created_at.strftime('%Y-%m-%d') %></th>
			                	<th style="width: 300px;"><%= link_to "#{(r.user.name_family_kanji + r.user.name_first_kanji)}", admins_user_path(r.user.id) %></th>
			                	<th id="star-rate-<%= r.id %>"></th>
						          <script>
						          $('#star-rate-<%= r.id %>').raty({
						            size: 36,
						            starOff:  '<%= ('star-off.png') %>',
						            starOn : '<%= ('star-on.png') %>',
						            starHalf: '<%= ('star-half.png') %>',
						            half: true,
						            readOnly: true,
						            score: <%= r.satisfaction %>,
						          });
						          </script>
							</tr>
					    	<% end %>
					    </table>
						<div class="pagenate"><%= paginate @reviews %></div>
		      	  	</div>
		        </div>
		    </div>
		</div>
	</div>
	<script>
		$('#tab-contents .tab[id != "tab1"]').hide();
		$('#tab-menu a').on('click', function() {
		  $("#tab-contents .tab").hide();
		  $("#tab-menu .active").removeClass("active");
		  $(this).addClass("active");
		  $($(this).attr("href")).show();
		  return false;
		});
	</script>
</div>